name: Build

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install packages
        run: sudo apt-get update && sudo apt-get install -y make ruby

      - name: Install gems
        run: sudo gem install asciidoctor asciidoctor-pdf

      - name: Build
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: riscv-abi-manual.zip
          path: |
            build/riscv-abi.pdf
            build/riscv-abi.html

  draft-release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.1.8

      - name: Get current date
        id: date
        run: echo "RELEASE_DATE=$(date --utc +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2.1.0
        with:
          draft: true
          name: Draft release ${{ steps.date.outputs.RELEASE_DATE }}
          body: Snapshot (${{ github.sha }})
          files: |
            riscv-abi-manual.zip/riscv-abi.pdf
            riscv-abi-manual.zip/riscv-abi.html

  release:
    if: github.event_name == 'release' && github.event.action == 'created'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.1.8

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2.1.0
        with:
          files: |
            riscv-abi-manual.zip/riscv-abi.pdf
            riscv-abi-manual.zip/riscv-abi.html
